import prisma from "../services/db.ts";
const locations = [
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Kalaburagi City Center",
    address: "Super Market Road, Kalaburagi",
    pincode: "585101",
    landmark: "Near Central Market",
    lat: 17.3297,
    lng: 76.8343,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Super Market Area",
    address: "Super Market, Kalaburagi",
    pincode: "585101",
    landmark: "Main Shopping Area",
    lat: 17.3311,
    lng: 76.8359,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Alamand Chowk",
    address: "Alamand Chowk Road, Kalaburagi",
    pincode: "585101",
    landmark: "Major Junction",
    lat: 17.3278,
    lng: 76.8315,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Court Road Area",
    address: "Court Road, Kalaburagi",
    pincode: "585101",
    landmark: "District Court",
    lat: 17.3259,
    lng: 76.8368,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Station Road Area",
    address: "Station Road, Kalaburagi",
    pincode: "585102",
    landmark: "Near Railway Station",
    lat: 17.3396,
    lng: 76.8379,
  },

  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Sedam Road",
    address: "Sedam Road, Kalaburagi",
    pincode: "585105",
    landmark: "Ring Road Junction",
    lat: 17.3484,
    lng: 76.8552,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Jewargi Road",
    address: "Jewargi Road, Kalaburagi",
    pincode: "585102",
    landmark: "Highway Stretch",
    lat: 17.3194,
    lng: 76.8462,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Humnabad Road",
    address: "Humnabad Road, Kalaburagi",
    pincode: "585102",
    landmark: "Transport Office Area",
    lat: 17.3368,
    lng: 76.8589,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Ring Road North",
    address: "Ring Road North, Kalaburagi",
    pincode: "585105",
    landmark: "Outer Ring Road",
    lat: 17.3569,
    lng: 76.8454,
  },

  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "MSK Mill Area",
    address: "MSK Mill Road, Kalaburagi",
    pincode: "585102",
    landmark: "Old Mill",
    lat: 17.3215,
    lng: 76.8387,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Brahmpur",
    address: "Brahmpur Area, Kalaburagi",
    pincode: "585101",
    landmark: "Residential Locality",
    lat: 17.3332,
    lng: 76.8268,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Khaja Colony",
    address: "Khaja Colony Road, Kalaburagi",
    pincode: "585104",
    landmark: "Near Masjid",
    lat: 17.3164,
    lng: 76.8329,
  },

  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Rajapur Area",
    address: "Rajapur Road, Kalaburagi",
    pincode: "585103",
    landmark: "Residential Layout",
    lat: 17.3438,
    lng: 76.8257,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "KBN University Area",
    address: "KBN University Road, Kalaburagi",
    pincode: "585106",
    landmark: "University Campus",
    lat: 17.3701,
    lng: 76.8254,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Central Jail Road",
    address: "Central Jail Road, Kalaburagi",
    pincode: "585102",
    landmark: "Near Central Jail",
    lat: 17.3129,
    lng: 76.8496,
  },

  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "AIIMS Road",
    address: "AIIMS Road, Kalaburagi",
    pincode: "585106",
    landmark: "AIIMS Campus",
    lat: 17.3638,
    lng: 76.8431,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Airport Road",
    address: "Airport Road, Kalaburagi",
    pincode: "585106",
    landmark: "Airport Junction",
    lat: 17.3606,
    lng: 76.8392,
  },

  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Shanti Nagar",
    address: "Shanti Nagar, Kalaburagi",
    pincode: "585101",
    landmark: "Residential Colony",
    lat: 17.3282,
    lng: 76.8417,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Gandhi Nagar",
    address: "Gandhi Nagar, Kalaburagi",
    pincode: "585101",
    landmark: "Near Govt School",
    lat: 17.3306,
    lng: 76.8294,
  },

  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Ram Mandir Area",
    address: "Ram Mandir Road, Kalaburagi",
    pincode: "585101",
    landmark: "Ram Temple",
    lat: 17.3347,
    lng: 76.8332,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Market Yard Road",
    address: "Market Yard Road, Kalaburagi",
    pincode: "585102",
    landmark: "APMC Yard",
    lat: 17.3198,
    lng: 76.8425,
  },

  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Teachers Colony",
    address: "Teachers Colony, Kalaburagi",
    pincode: "585105",
    landmark: "Residential Layout",
    lat: 17.3506,
    lng: 76.8479,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Vijay Nagar",
    address: "Vijay Nagar, Kalaburagi",
    pincode: "585105",
    landmark: "Near Park",
    lat: 17.3528,
    lng: 76.8521,
  },

  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Basava Nagar",
    address: "Basava Nagar, Kalaburagi",
    pincode: "585103",
    landmark: "Residential Area",
    lat: 17.3417,
    lng: 76.8196,
  },
  {
    state: "Karnataka",
    district: "Kalaburagi",
    city: "Kalaburagi",
    locationName: "Ring Road East",
    address: "Ring Road East, Kalaburagi",
    pincode: "585105",
    landmark: "Bypass Stretch",
    lat: 17.3499,
    lng: 76.8614,
  },
];
const seed = async () => {
  const seeded = await prisma.location.createMany({
    data: locations,
  });
  if (seeded.count === locations.length) {
    console.log("Seeded successfully");
  } else {
    console.log("Failed to seed");
  }
};

seed();
